include themes/tokyonight-night.conf
include symbols_map.conf

background #000000
background_opacity 0.8
background_blur 20

font_size 17
font_family Maple Mono NF Light
italic_font Victor Mono Light Italic
bold_italic_font Victor Mono Bold Italic
bold_font auto
# modify_font cell_height 110%

cursor_shape beam
cursor_blink_interval 0

allow_remote_control yes
enable_audio_bell no
disable_ligatures never
hide_window_decorations titlebar-only
editor nvim
term xterm-256color

macos_option_as_alt both

map cmd+h send_key alt+h
map cmd+j send_key alt+j
map cmd+k send_key alt+k
map cmd+l send_key alt+l
