symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+E0A0-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+F000-U+F2E0,U+F500-U+FD46,U+F0001-U+F1AF0 Symbols Nerd Font Mono
symbol_map U+F406 Hack Nerd Font
# U+F015 -> home
