gui:
  theme:
    activeBorderColor:
      - "#ff9e64"
      - bold
    inactiveBorderColor:
      - "#565f89"
    selectedLineBgColor:
      - "#2f334d"
    searchingActiveBorderColor:
      - "#ff9e64"
      - bold
    optionsTextColor:
      - "#7dcfff"
    cherryPickedCommitBgColor:
      - "#3b4261"
    cherryPickedCommitFgColor:
      - "#bb9af7"
    unstagedChangesColor:
      - "#f7768e"
    defaultFgColor:
      - "#c0caf5"

  showFileTree: true # for rendering changes files in a tree format
  showListFooter: true # for seeing the '5 of 20' message in list panels
  showRandomTip: true
  showBottomLine: true # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: true

disableStartupPopups: true
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
