gui:
  theme:
    activeBorderColor:
      - yellow
      - bold
    inactiveBorderColor:
      - blue
    selectedLineBgColor:
      - reverse

  showFileTree: true # for rendering changes files in a tree format
  showListFooter: true # for seeing the '5 of 20' message in list panels
  showRandomTip: true
  showBottomLine: true # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: true

disableStartupPopups: true
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
