#!/usr/bin/env bash

yay -S xdg-desktop-portal \
  xdg-desktop-portal-hyprland \
  xdg-desktop-portal-gtk \
  xdg-user-dirs \
  nwg-displays \
  nwg-look \
  rofi-wayland \
  waybar-git \
  networkmanager \
  network-manager-applet \
  blueman \
  bluez \
  bluez-utils \
  udiskie \
  polkit-kde-agent \
  libreoffice-fresh \
  keyd \
  dolphin \
  kvantum \
  kvantum-qt5 \
  kvantum-qt6-git \
  tokyonight-gtk-theme-git \
  catppuccin-gtk-theme-mocha \
  tela-circle-icon-theme-all \
  bibata-cursor-git \
  kde-cli-tools \
  archlinux-xdg-menu \
  kservice5 \
  imagemagick \
  qt5-imageformats \
  ffmpeg \
  ffmpegthumbs \
  mpv \
  gwenview \
  ark \
  p7zip \
  unrar \
  hyprpicker \
  hypridle \
  hyprlock \
  wlogout \
  swaylock-effects \
  swaync \
  qt5-wayland \
  qt6-wayland \
  qt6ct \
  cliphist \
  swappy \
  wl-clipboard \
  wf-recorder \
  slurp \
  grimblast-git \
  libinput-gestures \
  pipewire-pulse \
  pipewire-audio \
  pipewire-jack \
  pipewire-alsa \
  wctl \
  pavucontrol \
  wireplumber \
  brightnessctl \
  pamixer \
  sddm \
  sddm-astronaut-theme \
  qt5-quickcontrols2 \
  qt5-graphicaleffects \
  qt5-svg \
  pacman-contrib

# sudo systemctl enable keyd.service
# sudo systemctl start keyd.service
